# Cross-compilation configuration

# Windows GNU target - static linking to avoid VCRUNTIME140.dll dependency
[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "target-feature=+crt-static"
]

# ARM64 Linux glibc - much more reliable than musl for complex C++ dependencies
[target.aarch64-unknown-linux-gnu]
# No special configuration needed - cross-rs handles this well



# x86_64 Linux musl - ensure static linking
[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=+crt-static"
]
